# Generated by Django 3.2.25 on 2025-12-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_newsletter_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='tags',
        ),
    ]
