# Generated by Django 3.2.25 on 2025-11-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20251111_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(null=True, to='blog.Category'),
        ),
    ]
